ERROR:client.infrastructure.adapters.inbound.ui_adapter:Ошибка при получении записей: Failed to fetch records: HTTPConnectionPool(host='server', port=8000): Max retries exceeded with url: /records?page=1&limit=10 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F396517B60>: Failed to resolve 'server' ([Errno 11001] getaddrinfo failed)"))
ERROR:client.infrastructure.adapters.inbound.ui_adapter:Ошибка при получении записей: Failed to fetch records: HTTPConnectionPool(host='server', port=8000): Max retries exceeded with url: /records?page=1&limit=10 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000028EE4E97B60>: Failed to resolve 'server' ([Errno 11001] getaddrinfo failed)"))
INFO:client.infrastructure.adapters.inbound.ui_adapter:Record sent successfully
INFO:client.infrastructure.adapters.inbound.ui_adapter:Record sent successfully
INFO:infrastructure.adapters.inbound.ui_adapter:Record sent successfully
INFO:src.infrastructure.adapters.inbound.ui_adapter:Record sent successfully
